### ISSUE TITLE
bower module

### ISSUE THREAD

**Issue by darlanmendonca** [Kelbster/highlightjs-material-dark-theme#1]
hey man!! nice module

You consider publish their in bower?

If yes, I can do a PR

**Comment by darlanmendonca** [comment]
https://github.com/Kelbster/highlightjs-material-dark-theme/pull/2

**Comment by Kelbster** [comment]
Cool!
Approved and merged 👍

**Comment by Kelbster** [comment]
@darlanmendonca I updated the readme, you can now `bower install highlightjs-material-dark`

Thanks!

**Comment by darlanmendonca** [comment]
Thanks to you, is useful for all of us.

Just left two things to works

1. register the module in bower (I did)
```sh
bower register highlightjs-material-dark-theme https://github.com/Kelbster/highlightjs-material-dark-theme
```

2. Release a tag (just you can, because is that built in repository)
```sh
git tag -a v0.0.1 -m "release version 0.0.1"
```

Note, the version, is you who define, always you want publish, make a tag, and the version are available to be used in bower to everybody
